---
- name: PROXMOX | Ensure snippets directory exists
  ansible.builtin.file:
    path: "{{ proxmox_template__snippets_directory }}"
    state: directory
    owner: root
    group: root
    mode: "0750"

- name: PROXMOX | Ensure provision-template script exists
  ansible.builtin.template:
    src: provision-template.sh.j2
    dest: "{{ proxmox_template__snippets_directory }}/provision-template.sh"
    owner: root
    group: root
    mode: "0750"

- name: TOOLS | Run template script to create new provision_template_script
  ansible.builtin.command: /var/lib/vz/snippets/provision-template.sh
  when: run_provision_template_script is defined
