variable "vms" {
  description = "Map of vm configurations"
  type = map(object({
    target_node = string # The Proxmox node to host the VM
    vmid        = number # The unique VM ID
    hostname    = string # The name of the instance
    ip          = string # Ip address and subnet
    cores       = number # How many cores to allocate the VM
    memory      = number # Memory size
    size        = string # The size of the disk
    storage     = string # Which disk id to use
    onboot      = bool   # Automatically start the VM when the node starts
    state       = string # Can be "running", "started", "stopped". Option "started" will only start the vm on creation and won't fully manage the power state
    template    = string # The name of the template to clone
    full_clone  = bool   # true: an independant clone, false: a linked clone where a snapshot of the base vm is made
    hotplug     = string # Hotplug options for the VM. Can be "network", "disk", "usb", "memory", "cpu". Disabled with 0
    numa        = bool   # Enable NUMA support.  Required for hotplugging memory and CPU
  }))
  default = {
    docker = {
      target_node = "pve-node-01"
      vmid        = 300
      hostname    = "docker"
      ip          = "192.168.1.52/24"
      cores       = 4
      memory      = 3072
      size        = "20G"
      storage     = "local-zfs"
      onboot      = false
      state       = "started"
      template    = "template-ubuntu-24-04-cloud"
      full_clone  = true
      hotplug     = "disk,network,usb,memory,cpu"
      numa        = true
    },
    elastic = {
      target_node = "pve-node-01"
      vmid        = 301
      hostname    = "elastic"
      ip          = "192.168.1.55/24"
      cores       = 4
      memory      = 8196
      size        = "20G"
      storage     = "local-zfs"
      onboot      = false
      state       = "started"
      template    = "template-ubuntu-24-04-cloud"
      full_clone  = true
      hotplug     = "network,disk,usb"
      numa        = null
    }
    kube-01 = {
      target_node = "pve-node-01"
      vmid        = 302
      hostname    = "kube-01"
      ip          = "192.168.1.56/24"
      cores       = 2
      memory      = 2048
      size        = "10G"
      storage     = "local-zfs"
      onboot      = false
      state       = "started"
      template    = "template-ubuntu-24-04-cloud"
      full_clone  = true
      hotplug     = "network,disk,usb"
      numa        = null
    }
    kube-02 = {
      target_node = "pve-node-01"
      vmid        = 303
      hostname    = "kube-02"
      ip          = "192.168.1.57/24"
      cores       = 2
      memory      = 2048
      size        = "10G"
      storage     = "local-zfs"
      onboot      = false
      state       = "started"
      template    = "template-ubuntu-24-04-cloud"
      full_clone  = true
      hotplug     = "network,disk,usb"
      numa        = null
    }
    kube-03 = {
      target_node = "pve-node-01"
      vmid        = 304
      hostname    = "kube-03"
      ip          = "192.168.1.58/24"
      cores       = 2
      memory      = 2048
      size        = "10G"
      storage     = "local-zfs"
      onboot      = false
      state       = "started"
      template    = "template-ubuntu-24-04-cloud"
      full_clone  = true
      hotplug     = "network,disk,usb"
      numa        = null
    }
    nfs= {
      target_node = "pve-node-02"
      vmid        = 305
      hostname    = "nfs"
      ip          = "192.168.1.62/24"
      cores       = 1
      memory      = 512
      size        = "80G"
      storage     = "media"
      onboot      = true
      state       = "started"
      template    = "template-ubuntu-24-04-cloud"
      full_clone  = true
      hotplug     = "network,disk,usb"
      numa        = null
    }
  }
}
