---
- name: BIND | Ensure /etc/default/named is set to tcpip v4
  ansible.builtin.lineinfile:
    path: '/etc/default/named'
    regexp: '^OPTIONS="-u bind"'
    line: 'OPTIONS="-u bind -4"'
    state: present

- name: BIND | Restart bind service
  ansible.builtin.service:
    name: bind9
    state: restarted
  notify: Restart bind

- name: BIND | Copy custom options file
  ansible.builtin.template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
    owner: root
    group: bind
    mode: "0644"
    backup: true

- name: BIND | Copy custom local file
  ansible.builtin.template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
    owner: root
    group: bind
    mode: "0644"
    backup: true

- name: BIND | Make the zones directory
  ansible.builtin.file:
    path: /var/lib/bind/zones
    owner: bind
    group: bind
    state: directory
    mode: '0770'

- name: BIND | Copy forward zone files
  ansible.builtin.template:
    src: db.forward.{{ item }}.j2
    dest: /var/lib/bind/zones/db.{{ item }}
    owner: bind
    group: bind
    mode: "0770"
  with_items:
    - "{{ external_dns_domain }}"
    - "{{ global_dns_domain }}"
  when: bind__skip_zone_copy is not defined

- name: BIND | Copy reverse zone file
  ansible.builtin.template:
    src: db.reverse.j2
    dest: /var/lib/bind/zones/db.1.168.192
    owner: bind
    group: bind
    mode: "0770"
  when: bind__skip_zone_copy is not defined

- name: BIND | BIND | Restart bind service
  ansible.builtin.service:
    name: bind9
    state: restarted
  notify: Restart bind
