zabbix__mysql_db__enc: ENC[AES256_GCM,data:3cpvtlRS,iv:+a2LaWRFx3VKnLUPN5Bc8bpeAcONy0jv65/9wIowtJQ=,tag:ri2GyOLezCpFTNygIefDKw==,type:str]
zabbix__mysql_user_name__enc: ENC[AES256_GCM,data:8t7GQQKb,iv:VPv+7Xh7rYP+FGdYzc3/ILWLn6TDHHRBh6+65mU71CQ=,tag:3HoezYaoUw1I3jvGVTKSNg==,type:str]
zabbix__mysql_user_password__enc: ENC[AES256_GCM,data:E3oi4OcDJmj0+RsApekMUQ==,iv:L4JGzuWUCj1qX3ZCd499TW4KCGyfzRer1WkzGr6OD8s=,tag:TM5+qPREuOj6oq3ydlnIBg==,type:str]
zabbix__frontend_port: "8080"
zabbix_agent2__disable_auto_create_host: true
zabbix_agent2__hostname: Zabbix server
zabbix_agent2__server: 127.0.0.1
zabbix_agent2__server_active: 127.0.0.1
packages__custom_packages:
    - acl
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-02-22T17:26:15Z"
    mac: ENC[AES256_GCM,data:/cAIgasmJAtAtL/uyLcKHuxK4UG0GoLG0XvulOBxX0ZPdSP83mcGY76ifzeRwT2DdagRT8XYjp0HLCaRuCU1LLOvRxrN7OcnStgzcsfOyN2Y/M6ef8Rt0fXFP44rtq89DCWD9WtKaoRnQ0frWuCdtEvIiUeH6Oh0rutM9qsXdp4=,iv:Ri45aFtQRAcKCxXg4PW00K8MePZgzG708mpKAdHXgpI=,tag:Dv95TU0mrsmDaVriDg6pKA==,type:str]
    pgp:
        - created_at: "2025-02-22T17:26:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5xFaLh+EJKkAQwAsp18gJYDGVclRvROh+feuslmdCeqZvUrpdyCieSdGngh
            +rl5nUsPRmOoST389wU2EcsvNG9SyKB7LNtGXPQ17iFmpjzCBRVLXCDZhayaZlZY
            8Cz8/XrIHOoTiSUL1gByCP8wp1QNXLNlWuC5DDPDDGMvY3DvHXiNkHhr1/p9M6vG
            sXnTQbqCYXnvFXjR7xw2NgaRFGrKHBwbvAHgPd2HQb0LqPjz7IsGDiL2Twz4S6WW
            vLQKqXpLv2qrChifafchQJkXLNujtg7tSs9FHKqDHy2FhULB5V5QqcQmuopSHEvn
            VyQiizzh6M5v9XuS8Tcsa/whPXXpjXohHqVty6aFZ3b0jd8HLzaxBdaqEfOVt1tP
            I2p7cYPuswIOZtt6AnMDfm84p0LimlmhHf3egzlNFLmynVk1dVa48K4Y045f/prj
            scd4P1QZm+S01cxClvTm4q2cA+l7YivaZWg1pE7mVnDGn0OCX+KaxLb0hYZjWf/W
            G3yTZJOnF0aH2ZxnoGgU1GgBCQIQa3h4zdY9JWPg1SL4tNovVO7SdzJ4/sGHgNhQ
            kV9kJDsvb+W/yPMi2OuzcW5EiLTJFWyS4rQIzyt5qk5qXVvRPG1odroRrzQ3bleE
            xxgrOJWvLbVDAVwNGi0iq1wEsGTDuvseMQ==
            =yfq5
            -----END PGP MESSAGE-----
          fp: 14C605DAE8C937F3301EAC6A5F486CD6B1ACA8C4
    encrypted_suffix: __enc
    version: 3.9.4
