---
- name: WAZUH | Ensure wazuh-agent is installed
  ansible.builtin.package:
    name: "wazuh-agent"
    state: present
    update_cache: true
  when: is_wazuh_server is not defined

- name: WAZUH | Configure Wazuh agent
  ansible.builtin.lineinfile:
    path: /var/ossec/etc/ossec.conf
    regexp: '(<address>)(.*)(</address>)'
    line: '<address>{{ wazuh__manager_ip }}</address>'

- name: WAZUH | Start wazuh-agent
  ansible.builtin.systemd:
    name: wazuh-agent
    enabled: true
    state: restarted
