---
- name: DNSMASQ | Ensure package is installed
  ansible.builtin.apt:
    name:
      - dnsmasq
    state: present

- name: DNSMASQ | Ensure dnsmasq configuration file is present
  ansible.builtin.template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    backup: true
    owner: root
    group: root
    mode: "0644"
  tags: dnsmasq_conf

- name: DNSMASQ | Change the link of systemd-resolved to avoid confict on port 53
  ansible.builtin.file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: true

- name: DNSMASQ | Add entries to hosts file
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
  with_items: "{{ dnsmasq__hosts_entries }}"
  tags: dnsmasq_hosts

- name: DNSMASQ | Add entries /etc/default/dnsmasq
  ansible.builtin.lineinfile:
    path: /etc/default/dnsmasq
    line: "{{ item }}"
  with_items: "{{ dnsmasq__etc_default_dnsmasq_entries }}"
  tags: dnsmasq_hosts

- name: DNSMASQ | Copy the dnsmasq-resolv.conf file
  ansible.builtin.template:
    src: dnsmasq-resolv.conf.j2
    dest: /etc/dnsmasq-resolv.conf
    backup: true
    owner: root
    group: root
    mode: "0644"

- name: DNSMASQ | Ensure dnsmasq service is running and enabled
  ansible.builtin.service:
    name: dnsmasq
    state: restarted
    enabled: true
  notify: Restart dnsmasq
  tags: services
