---
- name: Restart Zabbix services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
  loop:
    - zabbix-server
    - nginx
    - php8.3-fpm

- name: Enable zabbix_backup.timer
  ansible.builtin.systemd:
    name: zabbix_backup.timer
    enabled: true

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
