---
- name: REPOSITORIES | Gitlab | Download Gitlab repository package
  ansible.builtin.get_url:
    url: '{{ gitlab__debian_repo_download_url }}'
    dest: '{{ gitlab__debian_repo_download_file }}'
    mode: "0750"
  when: ansible_os_family == "Debian"

- name: REPOSITORIES | Gitlab | Install Gitlab repository package
  ansible.builtin.command::
    cmd: './{{ gitlab__debian_repo_download_file }}'
