---
- name: DOCKER | Download Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: DOCKER | Add Docker repository to apt sources
  ansible.builtin.apt_repository:
    repo: >
      deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc]
      https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
  when: ansible_architecture == "x86_64"

- name: DOCKER | Ensure docker packages are installed
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true

- name: DOCKER | Ensure docker group is present
  ansible.builtin.group:
    name: docker
    state: present

- name: DOCKER | Ensure user group membership for user
  ansible.builtin.user:
    name: michael
    groups: docker
    append: true

- name: DOCKER | Get docker zabbix agent from zabbix-agent2 role
  ansible.builtin.include_role:
    name: zabbix-agent2
    apply:
      tags:
        - zabbix_docker_plugin

- name: DOCKER | Prune unused Docker objects
  community.docker.docker_prune:
    containers: true
    images: true
    volumes: true
    networks: true
  when: docker__prune
