---
- name: DOCKER | Pull the latest portainer-ce image
  community.docker.docker_image:
    name: portainer/portainer-ce:latest
    source: pull

- name: DOCKER | Ensure portainer volume is present
  community.docker.docker_volume:
    name: portainer_data
    state: present

- name: DOCKER | Run portainer container
  community.docker.docker_container:
    name: portainer
    image: portainer/portainer-ce:latest
    state: started
    restart_policy: "unless-stopped"
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
