---
- name: TOOLS | Ping hosts
  hosts: all
  gather_facts: false
  tasks:
    - name: Ping all hosts
      ansible.builtin.ping:
  tags: ping

- name: TOOLS | Gather facts
  hosts: all
  gather_facts: true
  tasks:
    - name: Show ansible gather_facts, use with --limit option
      ansible.builtin.debug:
        var: ansible_facts
  tags: facts

- name: TOOLS | Ensure provision template script is on PVE
  hosts: hypervisor
  become: true
  roles:
    - {role: proxmox-template, tags: provision_template_script}

- name: TOOLS | Display all instances
  hosts: hypervisor
  become: true
  tasks:
    - name: Run pct list
      ansible.builtin.command: pct list
      register: pct_output

    - name: Show pct list output
      ansible.builtin.debug:
        var: pct_output.stdout_lines

    - name: Run qm list
      ansible.builtin.command: qm list
      register: qm_output

    - name: Show qm list output
      ansible.builtin.debug:
        var: qm_output.stdout_lines
  tags: show_instances

- name: TOOLS | Patch servers
  hosts: all
  become: true
  tasks:
    - name: Check for upgradable packages
      ansible.builtin.command: apt list --upgradable
      register: upgradable_packages

    - name: Display upgradable packages
      ansible.builtin.debug:
        var: upgradable_packages.stdout_lines

    - name: Pause for confirmation
      ansible.builtin.pause:
        prompt: "Do you want to continue with the package update? (yes/no)"
      register: pause_result

    - name: Update all packages to their latest version
      ansible.builtin.apt:
        name: "*"
        state: latest
      when: pause_result.user_input == 'yes'
  tags: patch_servers
