---
- name: CONTAINER | Ensure elastic network is created
  community.docker.docker_network:
    name: elastic
    state: present
  tags: kibana

- name: CONTAINER | Pull the latest Kibana image
  community.docker.docker_image:
    name: docker.elastic.co/kibana/kibana:8.17.2
    source: pull
  tags: kibana

- name: CONTAINER | Run Kibana container
  community.docker.docker_container:
    name: kib01
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.2
    state: started
    restart_policy: "unless-stopped"
    ports:
      - "5601:5601"
    memory: "4G"
    env:
      ELASTICSEARCH_HOSTS: "http://es01:9200"
  tags: kibana
