---
- name: CONTAINER | Ensure nginx_proxy_manager_network is created
  community.docker.docker_network:
    name: nginx_proxy_manager_network
    state: present
  tags: nginx_proxy_manager

- name: CONTAINER | Pull image for Nginx Proxy Manager
  community.docker.docker_image:
    name: jc21/nginx-proxy-manager:latest
    source: pull
  tags: nginx_proxy_manager

- name: CONTAINER | Ensure nginx_proxy_manager_data is present
  community.docker.docker_volume:
    name: nginx_proxy_manager_data
    state: present
  tags: nginx_proxy_manager

- name: CONTAINER | Ensure nginx_proxy_manager_letsencrypt is present
  community.docker.docker_volume:
    name: nginx_proxy_manager_letsencrypt
    state: present
  tags: nginx_proxy_manager

- name: CONTAINER | Run Nginx Proxy Manager container
  community.docker.docker_container:
    name: nginx_proxy_manager
    image: jc21/nginx-proxy-manager:latest
    state: started
    restart_policy: "unless-stopped"
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - nginx_proxy_manager_data:/data
      - nginx_proxy_manager_letsencrypt:/etc/letsencrypt
    env:
      INITIAL_ADMIN_EMAIL: michael_duke@outlook.com
      INITIAL_ADMIN_PASSWORD: "{{ nginx_proxy_manager__password__enc }}"
    networks:
      - name: nginx_proxy_manager_network
  tags: nginx_proxy_manager
